class AddKeys < ActiveRecord::Migration[5.2]
  def change
    add_foreign_key "duplicate_leads", "leads", name: "duplicate_leads_lead_id_fk"
    add_foreign_key "duplicate_leads", "leads", column: "reference_id", name: "duplicate_leads_reference_id_fk"
    add_foreign_key "engagement_policies", "properties", name: "engagement_policies_property_id_fk"
    add_foreign_key "engagement_policy_action_compliances", "scheduled_actions", name: "engagement_policy_action_compliances_scheduled_action_id_fk"
    add_foreign_key "engagement_policy_action_compliances", "users", name: "engagement_policy_action_compliances_user_id_fk"
    add_foreign_key "engagement_policy_actions", "engagement_policies", name: "engagement_policy_actions_engagement_policy_id_fk"
    add_foreign_key "engagement_policy_actions", "lead_actions", name: "engagement_policy_actions_lead_action_id_fk"
    add_foreign_key "lead_preferences", "leads", name: "lead_preferences_lead_id_fk"
    add_foreign_key "lead_preferences", "unit_types", name: "lead_preferences_unit_type_id_fk"
    add_foreign_key "lead_referrals", "leads", name: "lead_referrals_lead_id_fk"
    add_foreign_key "lead_referrals", "lead_referral_sources", name: "lead_referrals_lead_referral_source_id_fk"
    add_foreign_key "lead_transitions", "leads", name: "lead_transitions_lead_id_fk"
    add_foreign_key "leads", "lead_sources", name: "leads_lead_source_id_fk"
    add_foreign_key "leads", "properties", name: "leads_property_id_fk"
    add_foreign_key "leads", "users", name: "leads_user_id_fk"
    add_foreign_key "message_deliveries", "messages", name: "message_deliveries_message_id_fk"
    add_foreign_key "message_deliveries", "message_types", name: "message_deliveries_message_type_id_fk"
    add_foreign_key "message_delivery_adapters", "message_types", name: "message_delivery_adapters_message_type_id_fk"
    add_foreign_key "message_templates", "message_types", name: "message_templates_message_type_id_fk"
    add_foreign_key "message_templates", "users", name: "message_templates_user_id_fk"
    add_foreign_key "messages", "message_types", name: "messages_message_type_id_fk"
    add_foreign_key "messages", "users", column: "read_by_user_id", name: "messages_read_by_user_id_fk"
    add_foreign_key "messages", "users", name: "messages_user_id_fk"
    add_foreign_key "notes", "lead_actions", name: "notes_lead_action_id_fk"
    add_foreign_key "notes", "reasons", name: "notes_reason_id_fk"
    add_foreign_key "notes", "users", name: "notes_user_id_fk"
    add_foreign_key "properties", "teams", name: "properties_team_id_fk"
    add_foreign_key "property_listings", "properties", name: "property_listings_property_id_fk"
    add_foreign_key "property_listings", "lead_sources", column: "source_id", name: "property_listings_source_id_fk"
    add_foreign_key "property_users", "properties", name: "property_users_property_id_fk"
    add_foreign_key "property_users", "users", name: "property_users_user_id_fk"
    add_foreign_key "resident_details", "residents", name: "resident_details_resident_id_fk"
    add_foreign_key "residents", "leads", name: "residents_lead_id_fk"
    add_foreign_key "residents", "properties", name: "residents_property_id_fk"
    add_foreign_key "residents", "units", name: "residents_unit_id_fk"
    add_foreign_key "scheduled_actions", "engagement_policy_action_compliances", name: "scheduled_actions_engagement_policy_action_compliance_id_fk", on_delete: :cascade
    add_foreign_key "scheduled_actions", "engagement_policy_actions", name: "scheduled_actions_engagement_policy_action_id_fk"
    add_foreign_key "scheduled_actions", "lead_actions", name: "scheduled_actions_lead_action_id_fk"
    add_foreign_key "scheduled_actions", "scheduled_actions", column: "originator_id", name: "scheduled_actions_originator_id_fk"
    add_foreign_key "scheduled_actions", "reasons", name: "scheduled_actions_reason_id_fk"
    add_foreign_key "scheduled_actions", "users", name: "scheduled_actions_user_id_fk"
    add_foreign_key "team_users", "teams", name: "team_users_team_id_fk"
    add_foreign_key "team_users", "teamroles", name: "team_users_teamrole_id_fk"
    add_foreign_key "team_users", "users", name: "team_users_user_id_fk"
    add_foreign_key "unit_types", "properties", name: "unit_types_property_id_fk"
    add_foreign_key "units", "properties", name: "units_property_id_fk"
    add_foreign_key "units", "rental_types", name: "units_rental_type_id_fk"
    add_foreign_key "units", "unit_types", name: "units_unit_type_id_fk"
    add_foreign_key "user_profiles", "users", name: "user_profiles_user_id_fk"
    add_foreign_key "users", "roles", name: "users_role_id_fk"
  end
end
